# Generated by Django 5.1.4 on 2024-12-25 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Con',
            new_name='Contact',
        ),
    ]
